import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-l from-green-950 to-green-200">
        <div>
          <h1 className="text-slate-100">Hello World</h1>
        </div>
      </main>
    </>
  );
}
